sonar.projectKey=ai-ecommerce
sonar.projectName=AI Ecommerce Platform

sonar.sources=backend/app,frontend/src

sonar.exclusions=**/node_modules/**,**/dist/**

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11
