apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
  namespace: ai-ecommerce
spec:
  type: NodePort
  selector:
    app: ai-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080